# path to  oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# adds custom location with themes & set up theme
ZSH_CUSTOM=~/Dropbox/configs/zsh
ZSH_THEME="uncharted"

# here goes plugins
plugins=(extract # easy archive extraction: extract foo.zip
         colored-man-pages # pretty man pages
         command-not-found # suggest package name when not found

         # completition
         git
         docker
         node
         npm

         # python related
         celery
         django
         fabric
         pip
         python
         virtualenv

         # mac
         brew
         osx
         )

source ~/.oh-my-zsh/oh-my-zsh.sh

# aliases
source ~/Dropbox/configs/zsh/aliases.cfg


if [ "$(uname 2> /dev/null)" = "Linux" ]; then
    source ~/Dropbox/configs/zsh/work_settings.cfg
fi


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
