# path to  oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# adds custom location with themes & set up theme
ZSH_CUSTOM=~/configs/zsh
ZSH_THEME="uncharted"

# here goes plugins
plugins=(extract # easy archive extraction: extract foo.zip
         colored-man-pages # pretty man pages
         command-not-found # suggest package name when not found

         # completition
         git
         docker
         node
         npm

         # python related
         celery
         django
         fabric
         pip
         python
         virtualenv

         # mac
         brew
         osx
         )

source ~/.oh-my-zsh/oh-my-zsh.sh

# aliases
source ~/configs/zsh/aliases.cfg

# node version manager script 
export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

 source ~/configs/zsh/work_settings.cfg

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
